# Generated by Django 5.2.5 on 2025-10-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0095_repopulate_user_number_of_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
